Add the support of the sequence functions
cloudspannerecosystem/memefish pull request #63
Opened 2023-08-24 07:38 UTC by git-hulk

For more information can refer: https://cloud.google.com/spanner/docs/reference/standard-sql/sequence_functions

2023-08-28 06:15 UTC, makenowjust requested changes
Thanks!

Some minor coding style fixes are required.

2023-08-28 06:15 UTC, makenowjust commented on ast/ast.go
> +	Name     *Ident
Please add empty lines between pos/end comments and `token.Pos` fields.

```suggestion
	// pos = Sequence
	// end = Name.end

	Sequence token.Pos // position of "SEQUENCE" keyword

	Name     *Ident
```

2023-08-28 06:15 UTC, makenowjust commented on ast/ast.go
> +// SEQUENCE {{.Name | sql}}
```suggestion
//	SEQUENCE {{.Name | sql}}
```

2023-08-28 06:21 UTC, git-hulk commented
> IMO, we should treat `SEQUENCE` expressions as argument modifiers like `INTERVAL`.
> 
> https://github.com/cloudspannerecosystem/memefish/blob/1b120de904be1345085ee862d3d061476dc2db2f/ast/ast.go#L881-L896
> 
> However, adding new fileds to `Arg` seems bad to me. We should split `Arg` to a new interface `Arg` and the following three `Arg` types are needed:
> 
> * `IntervalArg`
> * `SequenceArg`
> * `ExprArg`
> 
> @git-hulk What do you think?

Good point, SequenceArg is exactly better than SequenceExpr. I will fix it soon.

2023-08-29 02:22 UTC, git-hulk commented on parser.go
> +	}
Sequence functions support GET_NEXT_SEQUENCE_VALUE and GET_INTERNAL_SEQUENCE_STATE, should I remove this special check?

2023-08-29 02:25 UTC, makenowjust commented on parser.go
> +	}
Perhaps, it is better.

2023-08-29 02:26 UTC, git-hulk commented on parser.go
> +	}
OK, let me change it into checking if it's an ident only.

2023-08-29 02:39 UTC, git-hulk commented on parser.go
> +	}
Done

2023-08-29 02:52 UTC, makenowjust commented
@git-hulk You assume all sequence functions take only one argument. It is true so far, but will it be true in the future? I think we should not accept such an assumption.

Could you check [my above comment](https://github.com/cloudspannerecosystem/memefish/pull/63#issuecomment-1695085601) again? I guess you have not understood this yet. Feel free to ask me if you have any questions/comments!

2023-08-29 03:13 UTC, git-hulk commented
> @git-hulk You assume all sequence functions take only one argument. It is true so far, but will it be true in the future? I think this assumption is poorly extensible and we should not accept such an assumption.
> 
> Could you check [my above comment](https://github.com/cloudspannerecosystem/memefish/pull/63#issuecomment-1695085601) again? I guess you have not understood this yet. Feel free to ask me if you have any questions/comments!

Yes, I misunderstood your comment. What you mean is to treat the Sequence function as a normal function, and then support parsing the sequence argument in parseArg, is that right?

2023-08-29 03:38 UTC, git-hulk commented
> @git-hulk Yes, that's right!

Done, a lot of sorry for misunderstanding your first comment.

2023-08-29 04:23 UTC, makenowjust commented
@git-hulk Okay. We encountered the next problem: mismatching between the AST definitions and the parser structure.

- - -

For now, `parseArg` can return one of three kinds of arguments: `SEQUENCE` arguments, `INTERVAL` arguments, or usual arguments. However, the `Arg` type only supports `INTERVAL` and usual arguments, but `SEQUENCE` arguments are represented by `Arg` of `SequenceArg` expression. In other words, `parseArg` is now `parseArgOrArgOfSequenceArg`. It sounds really bad to me.

The first solution to this problem is extending `Arg` to support `SEQUENCE` argument like:

```golang
type Arg struct {
	// pos = Interval || Sequence || Expr.pos
	// end = (IntervalUnit ?? Expr).end

	Interval token.Pos // position of "INTERVAL" keyword
    Sequence token.Pos // position of "SEQUENCE" keyword

	Expr         Expr
	IntervalUnit *Ident // optional
}
```

However, **it seems wrong to me** because this `Arg` can have two states at the same time. That is, when both `Interval` and `Sequence` of `Arg` are valid, it is not possible to determine which one should be treated correctly.

- - -

So, let's make `Arg` an interface and separate the roles of `Arg` (usual, `INTERVAL`, and `SEQUENCE` arguments).

```golang
type Arg interface {
	Node
	isArg()
}

func (ExprArg)     isArg()
func (IntervalArg) isArg()
func (SequenceArg) isArg()

type ExprArg struct {
	// pos = Expr.pos
	// end = Expr.end

	Expr Expr
}

type IntervalArg struct {
	// pos = Interval
	// end = Unit.end

	Interval token.Pos // position of "INTERVAL" keyword

	Expr Expr
	Unit *Ident
}

type SequenceArg struct {
	// pos = Sequence
	// end = Expr.end

	Sequence token.Pos // position of "SEQUENCE" keyword

	Expr Expr
}
```

Then, the `parseArg` should be rewritten:

```golang
func (p *Parser) parseArg() ast.Arg {
	if i := p.tryParseIntervalArg(); i != nil {
		return i
	}
	if s := p.tryParseSequenceArg(); s != nil {
		return s
	}
	return p.parseExprArg()
}
```

Finally, by implementing `tryParseIntervalArg`, `tryParseSequenceArg`, and `parseExprArg`, the AST definitions and the parser structure are matched.

- - -

Sorry for the long comment. This is my intention for the first comment. You could also feel free to ask me.

2023-08-29 05:04 UTC, git-hulk commented
I indeed thought about the solution when writing the last command, but it needs to refactor the struct arg into an interface so gave up this without asking. Thanks for your detail comment.

2023-08-29 09:06 UTC, git-hulk commented
@makenowjust Fixed it according to your comments, but one thing to be noticed is that will change the call expression's arguments structure.

2023-08-29 10:35 UTC, makenowjust approved these changes
Good. Thank you!

2023-08-29 12:16 UTC, git-hulk commented
Done, can help to take a look while you're free.

2023-08-29 12:30 UTC, makenowjust commented on ast/ast.go
> +	Unit *Ident
```suggestion
	Unit *Ident // optional
```

2023-08-29 12:31 UTC, makenowjust commented on ast/ast.go
> +// INTERVAL {{.Expr | sql}} {{.Unit | sqlOpt}}
```suggestion
//	INTERVAL {{.Expr | sql}} {{.Unit | sqlOpt}}
```

2023-08-29 12:31 UTC, makenowjust commented on ast/ast.go
> +// {{.Expr | sql}}
```suggestion
//	{{.Expr | sql}}
```

2023-08-29 12:31 UTC, makenowjust commented on ast/ast.go
> +// SEQUENCE {{.Expr | sql}}
```suggestion
//	SEQUENCE {{.Expr | sql}}
```

2023-08-29 12:48 UTC, merged

2023-08-29 12:49 UTC, makenowjust commented
@git-hulk Thank you, and sorry for letting you rewrite it many times.

2023-08-29 13:27 UTC, git-hulk commented
> @git-hulk Thank you, and sorry for letting you rewrite it many times.

My bad for missing so many places, thanks for pointing out.